sudo: required

services: docker

language: node_js

node_js:
  - node

branches:
  only:
    - master

script:
  - ssh-keygen -R 35.180.25.176
  - openssl aes-256-cbc -K $encrypted_34a133650a4c_key -iv $encrypted_34a133650a4c_iv -in private_key.enc -out ./private_key -d
  - ssh-keygen -R 35.180.25.176
  - scp StrictHostKeyChecking=no -i ./private_key ./docker-compose.yml ubuntu@35.180.25.176:/home/ubuntu/docker-compose.yml
  - ssh-keygen -R 35.180.25.176
  - scp StrictHostKeyChecking=no -i ./private_key ./api/dump.sql ubuntu@35.180.25.176:/home/ubuntu/dump.sql