sudo: required

services:
  - docker

language: node_js

node_js:
  - node

branches:
  only:
    - master

env:
  global:
    - ENCRYPTED_PRIVATE_KEY_PATH=./devops/prod/private_key.enc
    - PRIVATE_KEY_PATH=./private_key

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t $DOCKER_USERNAME/trio-test-client-app:latest -f ./devops/prod/client/Dockerfile ./client
  - docker build -t $DOCKER_USERNAME/trio-test-api-app:latest -f ./devops/prod/api/Dockerfile ./api
  - docker push $DOCKER_USERNAME/trio-test-client-app:latest
  - docker push $DOCKER_USERNAME/trio-test-api-app:latest
  - openssl aes-256-cbc -K $encrypted_34a133650a4c_key -iv $encrypted_34a133650a4c_iv -in $ENCRYPTED_PRIVATE_KEY_PATH -out $PRIVATE_KEY_PATH -d
  - ssh-keyscan -H $SERVER_URL
  - chmod -R 600 $PRIVATE_KEY_PATH
  - eval $(ssh-agent)
  - ssh-add $PRIVATE_KEY_PATH
  - scp -o StrictHostKeyChecking=no ./devops/prod/docker-compose.yml ubuntu@$SERVER_URL:/home/ubuntu/docker-compose.yml
  - scp -o StrictHostKeyChecking=no ./devops/prod/db/dump.sql ubuntu@$SERVER_URL:/home/ubuntu/dump.sql
  - ssh -i $PRIVATE_KEY_PATH ubuntu@$SERVER_URL 'bash -s' < ./devops/prod/deploy.sh
  - rm $PRIVATE_KEY_PATH
