sudo: required

services:
  - docker

language: node_js

node_js:
  - node

branches:
  only:
    - master

script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker build -t $DOCKER_USERNAME/trio-test-client-app:latest ./client
  - docker build -t $DOCKER_USERNAME/trio-test-api-app:latest ./api
  - docker push $DOCKER_USERNAME/trio-test-client-app:latest
  - docker push $DOCKER_USERNAME/trio-test-api-app:latest
  - openssl aes-256-cbc -K $encrypted_34a133650a4c_key -iv $encrypted_34a133650a4c_iv -in private_key.enc -out ./private_key -d
  - ssh-keyscan -H $SERVER_URL
  - chmod -R 600 ./private_key
  - eval $(ssh-agent)
  - ssh-add ./private_key
  - scp -o StrictHostKeyChecking=no ./docker-compose.yml ubuntu@$SERVER_URL:/home/ubuntu/docker-compose.yml
  - scp -o StrictHostKeyChecking=no ./api/dump.sql ubuntu@$SERVER_URL:/home/ubuntu/dump.sql
  - ssh -i ./private_key ubuntu@$SERVER_URL 'bash -s' < ./deploy.sh
  - rm ./private_key
