sudo: required

services: docker

language: node_js

node_js:
  - node

branches:
  only:
    - master

script:
  - openssl aes-256-cbc -K $encrypted_34a133650a4c_key -iv $encrypted_34a133650a4c_iv -in private_key.enc -out ./private_key -d